### ISSUE TITLE
Support GQA and flash_attn?

### ISSUE THREAD

**Issue by cyLi-Tiger** [thu-nics/MoA#2]
Hi, thanks for the great work! 

I haven't look into the details of the code but find [flash_attn](https://github.com/thu-nics/MoA/blob/266308c32b7b3fdae49009d752a696b4e4e34f0b/MoA/models/llama/modeling_llama.py#L132) and [GQA](https://github.com/thu-nics/MoA/blob/266308c32b7b3fdae49009d752a696b4e4e34f0b/MoA/models/llama/modeling_llama.py#L539) not supported. However, as mentioned in the paper, Llama-3-8B with GQA is benchmared and dense flashattention is also used during decode stage. I‘m confused with that.

**Comment by fuvty** [comment]
Hi @cyLi-Tiger, thanks for your interest in our work. The current code **does support flash attention 2**, as it is already supported by the original `transformers` library. You can use the dense flash attention by passing the argument `--attention_implementation flash_attention_2` or `--attention_implementation sdpa`(sdpa is the flash attention 1 implementation from PyTorch) in our evaluation scripts, like [this one](https://github.com/thu-nics/MoA/blob/master/scripts/evaluate/effieicency_test.py#L46). The [flash_attn notice](https://github.com/thu-nics/MoA/blob/266308c32b7b3fdae49009d752a696b4e4e34f0b/MoA/models/llama/modeling_llama.py#L132) you mentioned is only used to ensure  **correct masking with our sparse attention method**, not for dense attention methods.
As for GQA, the currently released code supports the accuracy tests of GQA-based models by converting a GQA model to MQA model with attention weight copy-paste. The sparse kernel that also natively supports GQA-based models will be released in the future.

**Comment by cyLi-Tiger** [comment]
Got it, thank you!

**Comment by shiyuetianqiang** [comment]
> Hi @cyLi-Tiger, thanks for your interest in our work. The current code **does support flash attention 2**, as it is already supported by the original `transformers` library. You can use the dense flash attention by passing the argument `--attention_implementation flash_attention_2` or `--attention_implementation sdpa`(sdpa is the flash attention 1 implementation from PyTorch) in our evaluation scripts, like [this one](https://github.com/thu-nics/MoA/blob/master/scripts/evaluate/effieicency_test.py#L46). The [flash_attn notice](https://github.com/thu-nics/MoA/blob/266308c32b7b3fdae49009d752a696b4e4e34f0b/MoA/models/llama/modeling_llama.py#L132) you mentioned is only used to ensure **correct masking with our sparse attention method**, not for dense attention methods. As for GQA, the currently released code supports the accuracy tests of GQA-based models by converting a GQA model to MQA model with attention weight copy-paste. The sparse kernel that also natively supports GQA-based models will be released in the future.

hi，sorry to ask this issue again
a GQA model has mults-groups, but a MQA model only has a group.
How to carry out paste-copy operation to convert a GQA model to MQA model?

**Comment by fuvty** [comment]
Sorry it's a typo,

> > Hi @cyLi-Tiger, thanks for your interest in our work. The current code **does support flash attention 2**, as it is already supported by the original `transformers` library. You can use the dense flash attention by passing the argument `--attention_implementation flash_attention_2` or `--attention_implementation sdpa`(sdpa is the flash attention 1 implementation from PyTorch) in our evaluation scripts, like [this one](https://github.com/thu-nics/MoA/blob/master/scripts/evaluate/effieicency_test.py#L46). The [flash_attn notice](https://github.com/thu-nics/MoA/blob/266308c32b7b3fdae49009d752a696b4e4e34f0b/MoA/models/llama/modeling_llama.py#L132) you mentioned is only used to ensure **correct masking with our sparse attention method**, not for dense attention methods. As for GQA, the currently released code supports the accuracy tests of GQA-based models by converting a GQA model to MQA model with attention weight copy-paste. The sparse kernel that also natively supports GQA-based models will be released in the future.
> 
> hi，sorry to ask this issue again a GQA model has mults-groups, but a MQA model only has a group. How to carry out paste-copy operation to convert a GQA model to MQA model?

Hi. Sorry it's a typo. I meant MHA with number of groups equal to number of heads
