### ISSUE TITLE
The compression plan for LLaMA 3.2 3B Instruct can not be used

### ISSUE THREAD

**Issue by HanzhiZhang-Ulrica** [thu-nics/MoA#8]
The compression plans of the model from huggingfave Llama-3.2-3B-Instruct:
1. Generated by README section **Automatic Search Pipeline**
2. In directories: **examples/meta-llama--Llama-3.2-3B-Instruct** (both moa_alpha_beta.json and streamingllm_alpha_beta.json)

cannot be used when processing scripts:
1. chat_demo.py
2. edited from README section **Evaluation/Apply MoA to LLM**

Here is the error (same for all mentioned conditions):
![image](https://github.com/user-attachments/assets/0d355784-4c0a-41ca-b87f-07af1722b820)

I just want to use the compressed models, so it is fine for me if you can directly provide me the compressed models' huggingface link for LLaMA 3.2 3B Instruct by moa_alpha_beta.json and streamingllm_alpha_beta.json. I appreciate your help!

**Comment by fuvty** [comment]
Hello, thanks for asking. Could you show me the specific command you used to run the code? 
For now, my best guess is that you are using the original GQA model without converting it to the MHA version that our released kernel currently supports.
To convert during the compression pipeline, you can add the `--is_gqa` parameter in the `scripts/pipeline/main.py`. During inference, convert the original model first with `scripts/helper/gqa_to_mha.py`, then use the converted one as the original model.

**Comment by HanzhiZhang-Ulrica** [comment]
The inference is working now after converting by `gqa_to_mha.py`! Thank you so much for your prompt response!
